In [2]:
import pandas as pd
import numpy as np

print("Python environment is working!")
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Python environment is working!
Pandas version: 3.0.6
NumPy version: 2.5.3

In [3]:
# Load the raw athlete dataset

df = pd.read_csv("../data/football_athlete_sessions_raw.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 4203
Columns: 17

In [4]:
# Basic dataset inspection

print("First 5 rows:")
display(df.head())

print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

First 5 rows:

,Athlete_ID,Age,Position,Date,Session_Type,Duration_Min,Distance_Km,Sprint_Distance_Km,Intensity_Score,Avg_Heart_Rate,Max_Heart_Rate,Sleep_Hours,Recovery_Score,Goals,Assists,Pass_Accuracy,Performance_Score
0,ATH001,24,Forward,2026-01-01,Training,72.190160,10.486127,0.858317,6.265863,156.432352,177.947083,6.627347,54.742084,0,0,76.455503,82.840779
1,ATH001,24,Forward,2026-01-02,Training,56.713488,5.842286,0.880233,5.796656,150.117578,166.569089,6.610056,60.283701,0,0,78.396168,78.233493
2,ATH001,24,Forward,2026-01-03,Training,74.838033,9.541248,1.030970,5.442289,141.549516,183.219394,8.174276,77.388648,1,0,87.290566,90.888348
3,ATH001,24,Forward,2026-01-04,Training,71.386756,9.834173,1.035382,6.039361,145.583406,171.389979,7.623911,75.374622,1,0,76.964695,88.169035
4,ATH001,24,Forward,2026-01-06,Training,72.867215,9.987261,1.372052,6.089617,147.046660,171.614600,8.003180,75.384015,1,0,78.129281,100.000000

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 4203 entries, 0 to 4202
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Athlete_ID          4203 non-null   str
 1   Age                 4203 non-null   int64
 2   Position            4203 non-null   str
 3   Date                4203 non-null   str
 4   Session_Type        4203 non-null   str
 5   Duration_Min        4203 non-null   float64
 6   Distance_Km         4203 non-null   float64
 7   Sprint_Distance_Km  4203 non-null   float64
 8   Intensity_Score     4203 non-null   float64
 9   Avg_Heart_Rate      4203 non-null   float64
 10  Max_Heart_Rate      4203 non-null   float64
 11  Sleep_Hours         4203 non-null   float64
 12  Recovery_Score      4203 non-null   float64
 13  Goals               4203 non-null   int64
 14  Assists             4203 non-null   int64
 15  Pass_Accuracy       4203 non-null   float64
 16  Performance_Score   4203 non-null   float64
dtypes: float64(10), int64(3), str(4)
memory usage: 691.4 KB

Missing values:
Athlete_ID            0
Age                   0
Position              0
Date                  0
Session_Type          0
Duration_Min          0
Distance_Km           0
Sprint_Distance_Km    0
Intensity_Score       0
Avg_Heart_Rate        0
Max_Heart_Rate        0
Sleep_Hours           0
Recovery_Score        0
Goals                 0
Assists               0
Pass_Accuracy         0
Performance_Score     0
dtype: int64

Duplicate rows: 0

In [5]:
# Check important numerical ranges

numeric_columns = [
    "Age",
    "Duration_Min",
    "Distance_Km",
    "Sprint_Distance_Km",
    "Intensity_Score",
    "Avg_Heart_Rate",
    "Max_Heart_Rate",
    "Sleep_Hours",
    "Recovery_Score",
    "Goals",
    "Assists",
    "Pass_Accuracy",
    "Performance_Score"
]

df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Age,4203.0,23.464906,3.375570,18.000000,20.000000,24.000000,27.000000,28.000000
Duration_Min,4203.0,74.658657,16.067564,21.629196,65.091617,76.031456,87.150979,116.733871
Distance_Km,4203.0,7.408517,2.195851,1.012114,6.307726,7.520794,8.738616,14.816934
Sprint_Distance_Km,4203.0,0.927104,0.340757,0.107435,0.699501,0.913684,1.150935,2.289790
Intensity_Score,4203.0,6.489429,1.513618,1.014881,5.635615,6.615689,7.604671,10.000000
Avg_Heart_Rate,4203.0,153.856626,10.380026,114.044966,147.472851,154.404168,161.112301,180.000000
Max_Heart_Rate,4203.0,178.752115,11.972385,133.962691,170.953141,179.351490,187.118106,205.000000
Sleep_Hours,4203.0,7.085900,0.887639,4.500000,6.479861,7.073099,7.693649,9.500000
Recovery_Score,4203.0,63.026572,11.745011,20.816694,55.085059,62.772209,71.010591,100.000000
Goals,4203.0,0.197002,0.443602,0.000000,0.000000,0.000000,0.000000,4.000000
Assists,4203.0,0.160837,0.395499,0.000000,0.000000,0.000000,0.000000,2.000000
Pass_Accuracy,4203.0,81.937194,6.060646,62.150623,77.795228,82.003761,86.041765,98.000000
Performance_Score,4203.0,83.849016,6.537185,63.458405,79.260420,83.641520,88.102140,100.000000

In [6]:
# Convert Date from text to datetime

df["Date"] = pd.to_datetime(df["Date"])

print("Date conversion successful!")
print("Date type:", df["Date"].dtype)
print("Date range:", df["Date"].min(), "to", df["Date"].max())

Date conversion successful!
Date type: datetime64[us]
Date range: 2026-01-01 00:00:00 to 2026-06-30 00:00:00

In [7]:
# Calculate daily training workload

df["Daily_Workload"] = (
    df["Duration_Min"] * df["Intensity_Score"]
).round(2)

print("Daily workload calculated successfully!")
display(
    df[
        ["Athlete_ID", "Date", "Duration_Min",
         "Intensity_Score", "Daily_Workload"]
    ].head(10)
)

Daily workload calculated successfully!

  Athlete_ID       Date  Duration_Min  Intensity_Score  Daily_Workload
0     ATH001 2026-01-01     72.190160         6.265863          452.33
1     ATH001 2026-01-02     56.713488         5.796656          328.75
2     ATH001 2026-01-03     74.838033         5.442289          407.29
3     ATH001 2026-01-04     71.386756         6.039361          431.13
4     ATH001 2026-01-06     72.867215         6.089617          443.73
5     ATH001 2026-01-07     63.955310         5.081250          324.97
6     ATH001 2026-01-10     89.351199         8.507960          760.20
7     ATH001 2026-01-11     79.146215         6.952936          550.30
8     ATH001 2026-01-12     67.089812         6.503937          436.35
9     ATH001 2026-01-13     58.177787         5.509464          320.53

In [8]:
# Make sure records are sorted correctly
df = df.sort_values(["Athlete_ID", "Date"]).reset_index(drop=True)

# Calculate rolling workload for each athlete
df["Rolling_7D_Workload"] = (
    df.groupby("Athlete_ID", group_keys=False)
      .apply(
          lambda group: group.set_index("Date")["Daily_Workload"]
          .rolling("7D")
          .sum()
          .set_axis(group.index)
      )
      .sort_index()
)

df["Rolling_28D_Workload"] = (
    df.groupby("Athlete_ID", group_keys=False)
      .apply(
          lambda group: group.set_index("Date")["Daily_Workload"]
          .rolling("28D")
          .sum()
          .set_axis(group.index)
      )
      .sort_index()
)

print("Rolling workload calculated successfully!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Daily_Workload",
            "Rolling_7D_Workload",
            "Rolling_28D_Workload"
        ]
    ].head(10)
)

Rolling workload calculated successfully!

,Athlete_ID,Date,Daily_Workload,Rolling_7D_Workload,Rolling_28D_Workload
0,ATH001,2026-01-01,452.33,452.33,452.33
1,ATH001,2026-01-02,328.75,781.08,781.08
2,ATH001,2026-01-03,407.29,1188.37,1188.37
3,ATH001,2026-01-04,431.13,1619.50,1619.50
4,ATH001,2026-01-06,443.73,2063.23,2063.23
5,ATH001,2026-01-07,324.97,2388.20,2388.20
6,ATH001,2026-01-10,760.20,1960.03,3148.40
7,ATH001,2026-01-11,550.30,2079.20,3698.70
8,ATH001,2026-01-12,436.35,2515.55,4135.05
9,ATH001,2026-01-13,320.53,2392.35,4455.58

In [9]:
# Calculate each athlete's personalized workload baseline
# using previous 28-day workload observations

df["Personal_Baseline"] = (
    df.groupby("Athlete_ID")["Rolling_28D_Workload"]
      .transform(
          lambda x: x.shift(1).rolling(window=10, min_periods=3).mean()
      )
)

print("Personalized baseline calculated successfully!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Rolling_7D_Workload",
            "Rolling_28D_Workload",
            "Personal_Baseline"
        ]
    ].head(15)
)

Personalized baseline calculated successfully!

,Athlete_ID,Date,Rolling_7D_Workload,Rolling_28D_Workload,Personal_Baseline
0,ATH001,2026-01-01,452.33,452.33,NaN
1,ATH001,2026-01-02,781.08,781.08,NaN
2,ATH001,2026-01-03,1188.37,1188.37,NaN
3,ATH001,2026-01-04,1619.50,1619.50,807.260000
4,ATH001,2026-01-06,2063.23,2063.23,1010.320000
5,ATH001,2026-01-07,2388.20,2388.20,1220.902000
6,ATH001,2026-01-10,1960.03,3148.40,1415.451667
7,ATH001,2026-01-11,2079.20,3698.70,1663.015714
8,ATH001,2026-01-12,2515.55,4135.05,1917.476250
9,ATH001,2026-01-13,2392.35,4455.58,2163.873333
10,ATH001,2026-01-14,2188.04,4576.24,2393.044000
11,ATH001,2026-01-15,3027.56,5415.76,2805.435000
12,ATH001,2026-01-16,3845.44,6233.64,3268.903000
13,ATH001,2026-01-17,3506.74,6655.14,3773.430000
14,ATH001,2026-01-18,3645.98,7344.68,4276.994000

In [10]:
# Calculate workload deviation from the athlete's personal baseline

df["Workload_Deviation"] = (
    (df["Rolling_7D_Workload"] - df["Personal_Baseline"])
    / df["Personal_Baseline"]
) * 100

df["Workload_Deviation"] = df["Workload_Deviation"].round(2)

print("Workload deviation calculated successfully!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Rolling_7D_Workload",
            "Personal_Baseline",
            "Workload_Deviation"
        ]
    ].head(20)
)

Workload deviation calculated successfully!

,Athlete_ID,Date,Rolling_7D_Workload,Personal_Baseline,Workload_Deviation
0,ATH001,2026-01-01,452.33,NaN,NaN
1,ATH001,2026-01-02,781.08,NaN,NaN
2,ATH001,2026-01-03,1188.37,NaN,NaN
3,ATH001,2026-01-04,1619.50,807.260000,100.62
4,ATH001,2026-01-06,2063.23,1010.320000,104.22
5,ATH001,2026-01-07,2388.20,1220.902000,95.61
6,ATH001,2026-01-10,1960.03,1415.451667,38.47
7,ATH001,2026-01-11,2079.20,1663.015714,25.03
8,ATH001,2026-01-12,2515.55,1917.476250,31.19
9,ATH001,2026-01-13,2392.35,2163.873333,10.56
10,ATH001,2026-01-14,2188.04,2393.044000,-8.57
11,ATH001,2026-01-15,3027.56,2805.435000,7.92
12,ATH001,2026-01-16,3845.44,3268.903000,17.64
13,ATH001,2026-01-17,3506.74,3773.430000,-7.07
14,ATH001,2026-01-18,3645.98,4276.994000,-14.75
15,ATH001,2026-01-19,4038.76,4805.139000,-15.95
16,ATH001,2026-01-20,4173.54,5383.700000,-22.48
17,ATH001,2026-01-21,4584.00,5931.772000,-22.72
18,ATH001,2026-01-22,4149.66,6477.926000,-35.94
19,ATH001,2026-01-23,3839.09,7020.963000,-45.32

In [11]:
# Detect workload anomalies

df["Anomaly_Flag"] = np.where(
    df["Workload_Deviation"].abs() >= 25,
    "Anomaly",
    "Normal"
)

print("Anomaly detection completed!")

print("\nAnomaly distribution:")
print(df["Anomaly_Flag"].value_counts())

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Rolling_7D_Workload",
            "Personal_Baseline",
            "Workload_Deviation",
            "Anomaly_Flag"
        ]
    ].tail(20)
)

Anomaly detection completed!

Anomaly distribution:
Anomaly_Flag
Anomaly    4005
Normal      198
Name: count, dtype: int64

,Athlete_ID,Date,Rolling_7D_Workload,Personal_Baseline,Workload_Deviation,Anomaly_Flag
4183,ATH030,2026-06-07,2791.61,12632.260,-77.90,Anomaly
4184,ATH030,2026-06-08,2617.30,12594.662,-79.22,Anomaly
4185,ATH030,2026-06-09,3195.29,12548.211,-74.54,Anomaly
4186,ATH030,2026-06-10,2952.90,12527.457,-76.43,Anomaly
4187,ATH030,2026-06-11,3087.98,12564.671,-75.42,Anomaly
4188,ATH030,2026-06-12,3109.01,12540.858,-75.21,Anomaly
4189,ATH030,2026-06-13,3646.48,12523.700,-70.88,Anomaly
4190,ATH030,2026-06-14,3802.32,12545.397,-69.69,Anomaly
4191,ATH030,2026-06-16,3543.27,12659.343,-72.01,Anomaly
4192,ATH030,2026-06-17,3746.54,12688.856,-70.47,Anomaly
4193,ATH030,2026-06-18,3924.81,12757.728,-69.24,Anomaly
4194,ATH030,2026-06-19,3838.42,12854.753,-70.14,Anomaly
4195,ATH030,2026-06-20,3809.31,12931.312,-70.54,Anomaly
4196,ATH030,2026-06-21,3697.80,13025.813,-71.61,Anomaly
4197,ATH030,2026-06-22,4479.48,13131.974,-65.89,Anomaly
4198,ATH030,2026-06-24,3639.05,13272.804,-72.58,Anomaly
4199,ATH030,2026-06-26,2979.29,13319.523,-77.63,Anomaly
4200,ATH030,2026-06-27,2840.85,13270.153,-78.59,Anomaly
4201,ATH030,2026-06-29,1658.51,13218.236,-87.45,Anomaly
4202,ATH030,2026-06-30,1882.88,13167.480,-85.70,Anomaly

In [12]:
# Calculate athlete readiness score

workload_balance = (
    100 - df["Workload_Deviation"].abs().clip(upper=100)
)

sleep_score = (
    df["Sleep_Hours"] / 9 * 100
).clip(upper=100)

df["Readiness_Score"] = (
    0.35 * df["Recovery_Score"]
    + 0.25 * df["Performance_Score"]
    + 0.20 * workload_balance
    + 0.20 * sleep_score
).clip(0, 100).round(2)

print("Readiness score calculated successfully!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Recovery_Score",
            "Sleep_Hours",
            "Workload_Deviation",
            "Performance_Score",
            "Readiness_Score"
        ]
    ].tail(15)
)

Readiness score calculated successfully!

,Athlete_ID,Date,Recovery_Score,Sleep_Hours,Workload_Deviation,Performance_Score,Readiness_Score
4188,ATH030,2026-06-12,65.738808,7.821467,-75.21,82.231814,65.91
4189,ATH030,2026-06-13,53.720916,7.537023,-70.88,82.955551,62.11
4190,ATH030,2026-06-14,80.922233,8.096323,-69.69,90.348503,74.96
4191,ATH030,2026-06-16,62.363582,7.212879,-72.01,82.349602,64.04
4192,ATH030,2026-06-17,74.967931,7.474414,-70.47,84.059301,69.77
4193,ATH030,2026-06-18,62.058873,7.033124,-69.24,93.123950,66.78
4194,ATH030,2026-06-19,60.417418,7.039696,-70.14,90.046071,65.27
4195,ATH030,2026-06-20,54.688938,7.095240,-70.54,84.859203,62.02
4196,ATH030,2026-06-21,49.189288,6.218149,-71.61,74.275795,55.28
4197,ATH030,2026-06-22,59.944664,7.311676,-65.89,94.943534,67.79
4198,ATH030,2026-06-24,68.527494,8.194235,-72.58,97.356829,72.02
4199,ATH030,2026-06-26,50.357188,6.034907,-77.63,75.658451,54.42
4200,ATH030,2026-06-27,50.059531,6.295834,-78.59,77.295734,55.12
4201,ATH030,2026-06-29,55.593448,6.302588,-87.45,70.177031,53.52
4202,ATH030,2026-06-30,45.086481,4.631822,-85.70,73.479259,47.30

In [13]:
# Create the target: next recorded performance score for each athlete

df = df.sort_values(["Athlete_ID", "Date"]).reset_index(drop=True)

df["Next_Performance_Score"] = (
    df.groupby("Athlete_ID")["Performance_Score"].shift(-1)
)

print("Prediction target created!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Performance_Score",
            "Next_Performance_Score"
        ]
    ].head(15)
)

Prediction target created!

   Athlete_ID       Date  Performance_Score  Next_Performance_Score
0      ATH001 2026-01-01          82.840779               78.233493
1      ATH001 2026-01-02          78.233493               90.888348
2      ATH001 2026-01-03          90.888348               88.169035
3      ATH001 2026-01-04          88.169035              100.000000
4      ATH001 2026-01-06         100.000000               79.120653
5      ATH001 2026-01-07          79.120653               70.541441
6      ATH001 2026-01-10          70.541441               83.271746
7      ATH001 2026-01-11          83.271746               89.215773
8      ATH001 2026-01-12          89.215773               76.582424
9      ATH001 2026-01-13          76.582424               76.027847
10     ATH001 2026-01-14          76.027847               90.244033
11     ATH001 2026-01-15          90.244033               96.583670
12     ATH001 2026-01-16          96.583670               88.969249
13     ATH001 2026-01-17          88.969249               84.105369
14     ATH001 2026-01-18          84.105369               89.340053

In [14]:
# Prepare data for machine learning

ml_df = df.dropna(subset=["Next_Performance_Score"]).copy()

features = [
    "Age",
    "Duration_Min",
    "Distance_Km",
    "Sprint_Distance_Km",
    "Intensity_Score",
    "Avg_Heart_Rate",
    "Max_Heart_Rate",
    "Sleep_Hours",
    "Recovery_Score",
    "Goals",
    "Assists",
    "Pass_Accuracy",
    "Daily_Workload",
    "Rolling_7D_Workload",
    "Rolling_28D_Workload",
    "Workload_Deviation"
]

X = ml_df[features]
y = ml_df["Next_Performance_Score"]

print("ML dataset prepared!")
print("Rows:", len(ml_df))
print("Features:", len(features))
print("Target:", "Next_Performance_Score")

ML dataset prepared!
Rows: 4173
Features: 16
Target: Next_Performance_Score

In [15]:
# Time-based train/test split

split_date = ml_df["Date"].quantile(0.80)

train_df = ml_df[ml_df["Date"] <= split_date].copy()
test_df = ml_df[ml_df["Date"] > split_date].copy()

X_train = train_df[features]
y_train = train_df["Next_Performance_Score"]

X_test = test_df[features]
y_test = test_df["Next_Performance_Score"]

print("Time-based split completed!")
print("Split date:", split_date)
print("Training records:", len(train_df))
print("Testing records:", len(test_df))
print("Training period:", train_df["Date"].min(), "to", train_df["Date"].max())
print("Testing period:", test_df["Date"].min(), "to", test_df["Date"].max())

Time-based split completed!
Split date: 2026-05-24 00:00:00
Training records: 3345
Testing records: 828
Training period: 2026-01-01 00:00:00 to 2026-05-24 00:00:00
Testing period: 2026-05-25 00:00:00 to 2026-06-29 00:00:00

In [16]:
# Baseline model: Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

baseline_model = LinearRegression()

baseline_model.fit(X_train, y_train)

baseline_predictions = baseline_model.predict(X_test)

baseline_mae = mean_absolute_error(y_test, baseline_predictions)
baseline_rmse = np.sqrt(mean_squared_error(y_test, baseline_predictions))
baseline_r2 = r2_score(y_test, baseline_predictions)

print("Baseline Model: Linear Regression")
print("----------------------------------")
print(f"MAE  : {baseline_mae:.2f}")
print(f"RMSE : {baseline_rmse:.2f}")
print(f"R²   : {baseline_r2:.3f}")

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [17]:
# Remove rows with missing values in any ML feature or target

ml_df = df.dropna(
    subset=features + ["Next_Performance_Score"]
).copy()

X = ml_df[features]
y = ml_df["Next_Performance_Score"]

# Recreate the time-based split after removing incomplete rows
split_date = ml_df["Date"].quantile(0.80)

train_df = ml_df[ml_df["Date"] <= split_date].copy()
test_df = ml_df[ml_df["Date"] > split_date].copy()

X_train = train_df[features]
y_train = train_df["Next_Performance_Score"]

X_test = test_df[features]
y_test = test_df["Next_Performance_Score"]

print("Clean ML dataset prepared!")
print("Usable records:", len(ml_df))
print("Training records:", len(train_df))
print("Testing records:", len(test_df))
print("Remaining missing values:", X_train.isna().sum().sum())

Clean ML dataset prepared!
Usable records: 4083
Training records: 3279
Testing records: 804
Remaining missing values: 0

In [18]:
# Baseline model: Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

baseline_model = LinearRegression()

baseline_model.fit(X_train, y_train)

baseline_predictions = baseline_model.predict(X_test)

baseline_mae = mean_absolute_error(y_test, baseline_predictions)
baseline_rmse = np.sqrt(mean_squared_error(y_test, baseline_predictions))
baseline_r2 = r2_score(y_test, baseline_predictions)

print("Baseline Model: Linear Regression")
print("----------------------------------")
print(f"MAE  : {baseline_mae:.2f}")
print(f"RMSE : {baseline_rmse:.2f}")
print(f"R²   : {baseline_r2:.3f}")

Baseline Model: Linear Regression
----------------------------------
MAE  : 5.27
RMSE : 6.54
R²   : -0.006

In [19]:
# Advanced model: XGBoost

from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)

xgb_model.fit(X_train, y_train)

xgb_predictions = xgb_model.predict(X_test)

xgb_mae = mean_absolute_error(y_test, xgb_predictions)
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_predictions))
xgb_r2 = r2_score(y_test, xgb_predictions)

print("Advanced Model: XGBoost")
print("------------------------")
print(f"MAE  : {xgb_mae:.2f}")
print(f"RMSE : {xgb_rmse:.2f}")
print(f"R²   : {xgb_r2:.3f}")

Advanced Model: XGBoost
------------------------
MAE  : 5.57
RMSE : 6.90
R²   : -0.119

In [20]:
# Compare baseline and advanced models

comparison = pd.DataFrame({
    "Model": ["Linear Regression", "XGBoost"],
    "MAE": [baseline_mae, xgb_mae],
    "RMSE": [baseline_rmse, xgb_rmse],
    "R2": [baseline_r2, xgb_r2]
})

display(comparison)

               Model       MAE      RMSE        R2
0  Linear Regression  5.274561  6.540188 -0.006186
1            XGBoost  5.571794  6.896373 -0.118766

In [21]:
# Analyze prediction errors

results = test_df[
    ["Athlete_ID", "Date", "Performance_Score", "Next_Performance_Score"]
].copy()

results["Linear_Prediction"] = baseline_predictions
results["XGBoost_Prediction"] = xgb_predictions

results["Linear_Absolute_Error"] = (
    results["Next_Performance_Score"] - results["Linear_Prediction"]
).abs()

results["XGBoost_Absolute_Error"] = (
    results["Next_Performance_Score"] - results["XGBoost_Prediction"]
).abs()

display(results.head(15))

print("Average Linear Regression error:",
      results["Linear_Absolute_Error"].mean().round(2))

print("Average XGBoost error:",
      results["XGBoost_Absolute_Error"].mean().round(2))

,Athlete_ID,Date,Performance_Score,Next_Performance_Score,Linear_Prediction,XGBoost_Prediction,Linear_Absolute_Error,XGBoost_Absolute_Error
107,ATH001,2026-05-26,93.219165,96.707061,83.405258,85.187386,13.301803,11.519676
108,ATH001,2026-05-27,96.707061,97.614005,83.826904,83.305626,13.787101,14.308379
109,ATH001,2026-05-28,97.614005,81.091762,84.237178,84.753716,3.145416,3.661953
110,ATH001,2026-05-29,81.091762,90.193940,84.072079,84.509972,6.121861,5.683968
111,ATH001,2026-05-30,90.193940,87.381593,83.821378,81.883598,3.560216,5.497995
112,ATH001,2026-05-31,87.381593,78.043385,83.891501,84.833656,5.848116,6.790271
113,ATH001,2026-06-01,78.043385,80.440539,83.704591,87.261162,3.264052,6.820623
114,ATH001,2026-06-02,80.440539,79.421414,85.615299,84.642029,6.193885,5.220615
115,ATH001,2026-06-03,79.421414,77.133819,84.710017,82.986252,7.576198,5.852433
116,ATH001,2026-06-04,77.133819,77.397286,83.301556,84.673546,5.904270,7.276260
117,ATH001,2026-06-05,77.397286,93.779592,84.698636,84.804977,9.080956,8.974615
118,ATH001,2026-06-07,93.779592,91.892827,83.466787,85.916084,8.426041,5.976743
119,ATH001,2026-06-08,91.892827,80.890766,84.120375,86.039543,3.229609,5.148777
120,ATH001,2026-06-10,80.890766,94.821740,83.539886,82.774818,11.281854,12.046922
121,ATH001,2026-06-12,94.821740,82.363439,84.062985,87.418755,1.699546,5.055315

Average Linear Regression error: 5.27
Average XGBoost error: 5.57

In [22]:
# Create additional athlete-history features

df = df.sort_values(["Athlete_ID", "Date"]).reset_index(drop=True)

df["Previous_Performance"] = (
    df.groupby("Athlete_ID")["Performance_Score"].shift(1)
)

df["Recent_Avg_Performance"] = (
    df.groupby("Athlete_ID")["Performance_Score"]
      .transform(lambda x: x.shift(1).rolling(7, min_periods=3).mean())
)

df["Recent_Avg_Recovery"] = (
    df.groupby("Athlete_ID")["Recovery_Score"]
      .transform(lambda x: x.shift(1).rolling(7, min_periods=3).mean())
)

df["Recent_Avg_Workload"] = (
    df.groupby("Athlete_ID")["Daily_Workload"]
      .transform(lambda x: x.shift(1).rolling(7, min_periods=3).mean())
)

print("Athlete-history features created!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Performance_Score",
            "Previous_Performance",
            "Recent_Avg_Performance",
            "Recent_Avg_Recovery",
            "Recent_Avg_Workload"
        ]
    ].head(15)
)

Athlete-history features created!

,Athlete_ID,Date,Performance_Score,Previous_Performance,Recent_Avg_Performance,Recent_Avg_Recovery,Recent_Avg_Workload
0,ATH001,2026-01-01,82.840779,NaN,NaN,NaN,NaN
1,ATH001,2026-01-02,78.233493,82.840779,NaN,NaN,NaN
2,ATH001,2026-01-03,90.888348,78.233493,NaN,NaN,NaN
3,ATH001,2026-01-04,88.169035,90.888348,83.987540,64.138144,396.123333
4,ATH001,2026-01-06,100.000000,88.169035,85.032914,66.947264,404.875000
5,ATH001,2026-01-07,79.120653,100.000000,88.026331,68.634614,412.646000
6,ATH001,2026-01-10,70.541441,79.120653,86.542051,69.780621,398.033333
7,ATH001,2026-01-11,83.271746,70.541441,84.256250,68.847075,449.771429
8,ATH001,2026-01-12,89.215773,83.271746,84.317817,70.154057,463.767143
9,ATH001,2026-01-13,76.582424,89.215773,85.886714,70.181211,479.138571
10,ATH001,2026-01-14,76.027847,76.582424,83.843010,68.054918,466.744286
11,ATH001,2026-01-15,90.244033,76.027847,82.108555,67.394489,422.391429
12,ATH001,2026-01-16,96.583670,90.244033,80.714845,67.906435,478.932857
13,ATH001,2026-01-17,88.969249,96.583670,83.209562,65.449106,549.348571
14,ATH001,2026-01-18,84.105369,88.969249,85.842106,66.115830,500.962857

In [23]:
# Prepare improved ML dataset

# Target = next performance
df["Next_Performance_Score"] = (
    df.groupby("Athlete_ID")["Performance_Score"].shift(-1)
)

# Features for prediction
feature_columns = [
    "Age",
    "Duration_Min",
    "Distance_Km",
    "Sprint_Distance_Km",
    "Intensity_Score",
    "Avg_Heart_Rate",
    "Max_Heart_Rate",
    "Sleep_Hours",
    "Recovery_Score",
    "Goals",
    "Assists",
    "Pass_Accuracy",
    "Performance_Score",
    "Rolling_7D_Workload",
    "Rolling_28D_Workload",
    "Previous_Performance",
    "Recent_Avg_Performance",
    "Recent_Avg_Recovery",
    "Recent_Avg_Workload"
]

# Keep only required columns
ml_df = df[feature_columns + ["Next_Performance_Score"]].copy()

# Remove rows where history/target is unavailable
ml_df = ml_df.dropna().reset_index(drop=True)

print("Improved ML dataset created!")
print("Rows:", len(ml_df))
print("Features:", len(feature_columns))

display(ml_df.head())

Improved ML dataset created!
Rows: 4083
Features: 19

,Age,Duration_Min,Distance_Km,Sprint_Distance_Km,Intensity_Score,Avg_Heart_Rate,Max_Heart_Rate,Sleep_Hours,Recovery_Score,Goals,Assists,Pass_Accuracy,Performance_Score,Rolling_7D_Workload,Rolling_28D_Workload,Previous_Performance,Recent_Avg_Performance,Recent_Avg_Recovery,Recent_Avg_Workload,Next_Performance_Score
0,24,71.386756,9.834173,1.035382,6.039361,145.583406,171.389979,7.623911,75.374622,1,0,76.964695,88.169035,1619.50,1619.50,90.888348,83.987540,64.138144,396.123333,100.000000
1,24,72.867215,9.987261,1.372052,6.089617,147.046660,171.614600,8.003180,75.384015,1,0,78.129281,100.000000,2063.23,2063.23,88.169035,85.032914,66.947264,404.875000,79.120653
2,24,63.955310,9.815904,1.234560,5.081250,144.389138,171.531813,8.430105,75.510656,0,0,77.149038,79.120653,2388.20,2388.20,100.000000,88.026331,68.634614,412.646000,70.541441
3,24,89.351199,11.484388,1.753317,8.507960,170.890988,194.035256,7.705813,63.245797,0,0,79.793046,70.541441,1960.03,3148.40,79.120653,86.542051,69.780621,398.033333,83.271746
4,24,79.146215,8.306741,0.906168,6.952936,166.148547,192.196014,7.331795,63.890959,1,0,75.564809,83.271746,2079.20,3698.70,70.541441,84.256250,68.847075,449.771429,89.215773

In [24]:
print("Missing values:")
print(ml_df.isnull().sum())

print("\nDataset shape:")
print(ml_df.shape)

print("\nTarget statistics:")
print(ml_df["Next_Performance_Score"].describe())

Missing values:
Age                       0
Duration_Min              0
Distance_Km               0
Sprint_Distance_Km        0
Intensity_Score           0
Avg_Heart_Rate            0
Max_Heart_Rate            0
Sleep_Hours               0
Recovery_Score            0
Goals                     0
Assists                   0
Pass_Accuracy             0
Performance_Score         0
Rolling_7D_Workload       0
Rolling_28D_Workload      0
Previous_Performance      0
Recent_Avg_Performance    0
Recent_Avg_Recovery       0
Recent_Avg_Workload       0
Next_Performance_Score    0
dtype: int64

Dataset shape:
(4083, 20)

Target statistics:
count    4083.000000
mean       83.837154
std         6.544181
min        63.458405
25%        79.226263
50%        83.616997
75%        88.097329
max       100.000000
Name: Next_Performance_Score, dtype: float64

In [25]:
print("Target:", "Next_Performance_Score")
print("Target range:", ml_df["Next_Performance_Score"].min(), "to", ml_df["Next_Performance_Score"].max())

print("\nFeature columns:")
print(list(X.columns))

print("\nX shape:", X.shape)
print("y shape:", y.shape)

Target: Next_Performance_Score
Target range: 63.45840543663829 to 100.0

Feature columns:
['Age', 'Duration_Min', 'Distance_Km', 'Sprint_Distance_Km', 'Intensity_Score', 'Avg_Heart_Rate', 'Max_Heart_Rate', 'Sleep_Hours', 'Recovery_Score', 'Goals', 'Assists', 'Pass_Accuracy', 'Daily_Workload', 'Rolling_7D_Workload', 'Rolling_28D_Workload', 'Workload_Deviation']

X shape: (4083, 16)
y shape: (4083,)

In [26]:
# Personalized athlete workload baseline

df = df.sort_values(["Athlete_ID", "Date"]).copy()

# Previous workload for each athlete
df["Previous_7D_Workload"] = (
    df.groupby("Athlete_ID")["Rolling_7D_Workload"]
      .shift(1)
)

# Personalized baseline = average of previous workload values
df["Personal_Workload_Baseline"] = (
    df.groupby("Athlete_ID")["Previous_7D_Workload"]
      .transform(lambda x: x.expanding().mean())
)

# Percentage deviation from personal baseline
df["Workload_Deviation_Pct"] = (
    (df["Rolling_7D_Workload"] - df["Personal_Workload_Baseline"])
    / df["Personal_Workload_Baseline"]
) * 100

print("Personalized baseline calculated successfully!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Rolling_7D_Workload",
            "Personal_Workload_Baseline",
            "Workload_Deviation_Pct"
        ]
    ].head(15)
)

Personalized baseline calculated successfully!

,Athlete_ID,Date,Rolling_7D_Workload,Personal_Workload_Baseline,Workload_Deviation_Pct
0,ATH001,2026-01-01,452.33,NaN,NaN
1,ATH001,2026-01-02,781.08,452.330000,72.679239
2,ATH001,2026-01-03,1188.37,616.705000,92.696670
3,ATH001,2026-01-04,1619.50,807.260000,100.616902
4,ATH001,2026-01-06,2063.23,1010.320000,104.215496
5,ATH001,2026-01-07,2388.20,1220.902000,95.609476
6,ATH001,2026-01-10,1960.03,1415.451667,38.473820
7,ATH001,2026-01-11,2079.20,1493.248571,39.240046
8,ATH001,2026-01-12,2515.55,1566.492500,60.584874
9,ATH001,2026-01-13,2392.35,1671.943333,43.087983
10,ATH001,2026-01-14,2188.04,1743.984000,25.462160
11,ATH001,2026-01-15,3027.56,1784.352727,69.672731
12,ATH001,2026-01-16,3845.44,1887.953333,103.683001
13,ATH001,2026-01-17,3506.74,2038.529231,72.023042
14,ATH001,2026-01-18,3645.98,2143.401429,70.102527

In [27]:
# Workload anomaly detection

df["Workload_Anomaly"] = (
    df["Workload_Deviation_Pct"].abs() > 20
)

df["Anomaly_Status"] = df["Workload_Anomaly"].map({
    True: "⚠️ Anomaly",
    False: "Normal"
})

print("Workload anomaly detection completed!")

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Rolling_7D_Workload",
            "Personal_Workload_Baseline",
            "Workload_Deviation_Pct",
            "Anomaly_Status"
        ]
    ].head(20)
)

print("\nTotal anomaly records:",
      df["Workload_Anomaly"].sum())

Workload anomaly detection completed!

,Athlete_ID,Date,Rolling_7D_Workload,Personal_Workload_Baseline,Workload_Deviation_Pct,Anomaly_Status
0,ATH001,2026-01-01,452.33,NaN,NaN,Normal
1,ATH001,2026-01-02,781.08,452.330000,72.679239,⚠️ Anomaly
2,ATH001,2026-01-03,1188.37,616.705000,92.696670,⚠️ Anomaly
3,ATH001,2026-01-04,1619.50,807.260000,100.616902,⚠️ Anomaly
4,ATH001,2026-01-06,2063.23,1010.320000,104.215496,⚠️ Anomaly
5,ATH001,2026-01-07,2388.20,1220.902000,95.609476,⚠️ Anomaly
6,ATH001,2026-01-10,1960.03,1415.451667,38.473820,⚠️ Anomaly
7,ATH001,2026-01-11,2079.20,1493.248571,39.240046,⚠️ Anomaly
8,ATH001,2026-01-12,2515.55,1566.492500,60.584874,⚠️ Anomaly
9,ATH001,2026-01-13,2392.35,1671.943333,43.087983,⚠️ Anomaly
10,ATH001,2026-01-14,2188.04,1743.984000,25.462160,⚠️ Anomaly
11,ATH001,2026-01-15,3027.56,1784.352727,69.672731,⚠️ Anomaly
12,ATH001,2026-01-16,3845.44,1887.953333,103.683001,⚠️ Anomaly
13,ATH001,2026-01-17,3506.74,2038.529231,72.023042,⚠️ Anomaly
14,ATH001,2026-01-18,3645.98,2143.401429,70.102527,⚠️ Anomaly
15,ATH001,2026-01-19,4038.76,2243.573333,80.014620,⚠️ Anomaly
16,ATH001,2026-01-20,4173.54,2355.772500,77.162268,⚠️ Anomaly
17,ATH001,2026-01-21,4584.00,2462.700000,86.137167,⚠️ Anomaly
18,ATH001,2026-01-22,4149.66,2580.550000,60.805255,⚠️ Anomaly
19,ATH001,2026-01-23,3839.09,2663.134737,44.156807,⚠️ Anomaly

Total anomaly records: 1960

In [28]:
print("Total records:", len(df))
print("Normal records:", (~df["Workload_Anomaly"]).sum())
print("Anomaly records:", df["Workload_Anomaly"].sum())

print("\nAnomaly percentage:",
      round(df["Workload_Anomaly"].mean() * 100, 2), "%")

print("\nSample anomalies:")

display(
    df[df["Workload_Anomaly"]][
        [
            "Athlete_ID",
            "Date",
            "Rolling_7D_Workload",
            "Personal_Workload_Baseline",
            "Workload_Deviation_Pct",
            "Anomaly_Status"
        ]
    ].head(15)
)

Total records: 4203
Normal records: 2243
Anomaly records: 1960

Anomaly percentage: 46.63 %

Sample anomalies:

,Athlete_ID,Date,Rolling_7D_Workload,Personal_Workload_Baseline,Workload_Deviation_Pct,Anomaly_Status
1,ATH001,2026-01-02,781.08,452.330000,72.679239,⚠️ Anomaly
2,ATH001,2026-01-03,1188.37,616.705000,92.696670,⚠️ Anomaly
3,ATH001,2026-01-04,1619.50,807.260000,100.616902,⚠️ Anomaly
4,ATH001,2026-01-06,2063.23,1010.320000,104.215496,⚠️ Anomaly
5,ATH001,2026-01-07,2388.20,1220.902000,95.609476,⚠️ Anomaly
6,ATH001,2026-01-10,1960.03,1415.451667,38.473820,⚠️ Anomaly
7,ATH001,2026-01-11,2079.20,1493.248571,39.240046,⚠️ Anomaly
8,ATH001,2026-01-12,2515.55,1566.492500,60.584874,⚠️ Anomaly
9,ATH001,2026-01-13,2392.35,1671.943333,43.087983,⚠️ Anomaly
10,ATH001,2026-01-14,2188.04,1743.984000,25.462160,⚠️ Anomaly
11,ATH001,2026-01-15,3027.56,1784.352727,69.672731,⚠️ Anomaly
12,ATH001,2026-01-16,3845.44,1887.953333,103.683001,⚠️ Anomaly
13,ATH001,2026-01-17,3506.74,2038.529231,72.023042,⚠️ Anomaly
14,ATH001,2026-01-18,3645.98,2143.401429,70.102527,⚠️ Anomaly
15,ATH001,2026-01-19,4038.76,2243.573333,80.014620,⚠️ Anomaly

In [29]:
# Improved personalized anomaly detection
# Use the athlete's previous 28 days as their personal baseline

df = df.sort_values(["Athlete_ID", "Date"]).copy()

# Previous 28-day workload baseline
df["Personal_28D_Baseline"] = (
    df.groupby("Athlete_ID")["Rolling_7D_Workload"]
      .transform(lambda x: x.shift(1).rolling(28, min_periods=7).mean())
)

# Personal workload standard deviation
df["Personal_28D_Std"] = (
    df.groupby("Athlete_ID")["Rolling_7D_Workload"]
      .transform(lambda x: x.shift(1).rolling(28, min_periods=7).std())
)

# Z-score: how unusual is the current workload for this athlete?
df["Workload_Z_Score"] = (
    (df["Rolling_7D_Workload"] - df["Personal_28D_Baseline"])
    / df["Personal_28D_Std"].replace(0, np.nan)
)

# Flag unusually high/low workload
df["Workload_Anomaly_Improved"] = (
    df["Workload_Z_Score"].abs() > 2
)

df["Anomaly_Status_Improved"] = df["Workload_Anomaly_Improved"].map({
    True: "⚠️ Anomaly",
    False: "Normal"
})

print("Improved personalized anomaly detection completed!")

print(
    "Anomaly records:",
    df["Workload_Anomaly_Improved"].sum()
)

print(
    "Anomaly percentage:",
    round(
        df["Workload_Anomaly_Improved"].mean() * 100,
        2
    ),
    "%"
)

display(
    df[
        [
            "Athlete_ID",
            "Date",
            "Rolling_7D_Workload",
            "Personal_28D_Baseline",
            "Workload_Z_Score",
            "Anomaly_Status_Improved"
        ]
    ].dropna().head(20)
)

Improved personalized anomaly detection completed!
Anomaly records: 316
Anomaly percentage: 7.52 %

,Athlete_ID,Date,Rolling_7D_Workload,Personal_28D_Baseline,Workload_Z_Score,Anomaly_Status_Improved
7,ATH001,2026-01-11,2079.20,1493.248571,0.822746,Normal
8,ATH001,2026-01-12,2515.55,1566.492500,1.373179,Normal
9,ATH001,2026-01-13,2392.35,1671.943333,1.000910,Normal
10,ATH001,2026-01-14,2188.04,1743.984000,0.620356,Normal
11,ATH001,2026-01-15,3027.56,1784.352727,1.796158,Normal
12,ATH001,2026-01-16,3845.44,1887.953333,2.605784,⚠️ Anomaly
13,ATH001,2026-01-17,3506.74,2038.529231,1.629297,Normal
14,ATH001,2026-01-18,3645.98,2143.401429,1.580744,Normal
15,ATH001,2026-01-19,4038.76,2243.573333,1.804663,Normal
16,ATH001,2026-01-20,4173.54,2355.772500,1.713826,Normal
17,ATH001,2026-01-21,4584.00,2462.700000,1.898082,Normal
18,ATH001,2026-01-22,4149.66,2580.550000,1.314199,Normal
19,ATH001,2026-01-23,3839.09,2663.134737,0.967957,Normal
20,ATH001,2026-01-24,3874.17,2721.932500,0.951189,Normal
21,ATH001,2026-01-25,3583.76,2776.800952,0.668472,Normal
22,ATH001,2026-01-27,2812.44,2813.480909,-0.000874,Normal
23,ATH001,2026-01-29,2221.88,2813.435652,-0.508559,Normal
24,ATH001,2026-01-30,2418.18,2788.787500,-0.323951,Normal
25,ATH001,2026-02-02,1871.62,2773.963200,-0.803952,Normal
26,ATH001,2026-02-03,1867.12,2739.257692,-0.782990,Normal